### ISSUE TITLE
Voucher Requirement

### ISSUE THREAD

**Issue by daminitandon** [SaturdayNeighborhoodHealthClinic/osler#129]
In order to submit work-ups, volunteers have to put in $1 under what the patient pays for the write-up to go through. Is there a way to fix this? Not sure what the other requirements are for this error->it may only be a problem when there is a non-zero voucher amount put in.

**Comment by justinrporter** [comment]
Yeah, we can do this easily. We have similar validation for the `voucher amount` field. Should we also not require this field to be filled?

@nakul2234 you should be able to fix this by removing the folliwng code from `workup/forms.py`:

```python
        if cleaned_data.get('got_voucher') and \
           not cleaned_data.get('patient_pays'):

            self.add_error('patient_pays', "If the patient recieved a " +
                           "voucher, specify the amount the patient pays.")

        if cleaned_data.get('got_imaging_voucher') and \
           not cleaned_data.get('imaging_voucher_amount'):

            self.add_error('imaging_voucher_amount', "If the patient recieved a " +
                           "imaging voucher, value of the voucher must be specified.")
```

**Comment by nakul2234** [comment]
Yeah, I think the less requirements we have the better. I'll make an issue_clean branch and lets update this Sunday.

**Comment by justinrporter** [comment]
Awesome. I'd like to move away from the `issue_clean` branch, though, because it isn't very transparent what it does. If we could, I think it would be better to make separate branches for issue fixes. In other words, a branch fixing this might be called `no-voucher-req` or something.

That way, you can work on separate bugfixes independently, and merge them independently, when they're ready. Does that make sense?

**Comment by nakul2234** [comment]
Yeah, sounds good!

**Comment by nakul2234** [comment]
#134
