### ISSUE TITLE
All patients view is slow to load

### ISSUE THREAD

**Issue by JoLBree** [SaturdayNeighborhoodHealthClinic/osler#165]
@zhouminerva @justinrporter 
Sooo, the scope for this is kinda large and will involve rewriting a lot of database queries
My suspicion is that because many columns of the all_patients table are not columns directly on the Patient table, what actually happens is

1. The [all_patients](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/views.py#L349) view asks for `patient_list = mymodels.Patient.objects.all().order_by('last_name')`. From a database query perspective, this should be 1 database hit to ask for `mymodels.Patient.objects.all()`, which gets all properties (columns) directly on the Patient database table
2. We get to the loop in the [template](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/templates/pttrack/all_patients.html#L18), which wants patient age, gender, list of case managers, clinic date and signer of the latest workup, history date of the last history, and status. Unfortunately, the database isn't prescient and doesn't know we want all these things not in the patient table, that are joined by foreign keys, etc.
3. Most of these properties are not on the Patient table. Thus for every patient, and for every property not directly on the Patient table, the templating makes a hit to the the database to get this joined property. [This django ref](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#select-related) describes this problem (and the general idea of the solution, which is to explicitly tell django to join/follow the relationship).
4. This is made worse by how some of these properties are computed. For instance, computing [status](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/models.py#L267) asks for `active_action_items`, `inactive_action_items`, and `done_action_items`. [Each of these](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/models.py#L238) makes a separate database query, filtering on the ActionItem table. Meaning that asking for a patient status makes 3 hits to the database.
5. Instead of making 1 database call, we end up making 1 + (num patients * >10). Assuming 500 patients that's > thousands of database hits
6. The all_patients view is slow because hits to the database are I/O, and I/O is costly time-wise

So, a major speedup will come from not hitting the database for every patient (as long as we take out the 500, it's totally okay to hit the db 10 times). Meaning everything the tables needs, we need to explicitly pull upfront. There are two approaches I'm thinking about, and with the complexity of a lot of these queries I'm thinking of going for a hybrid:

1. Slowly fold each property into a loooong all patients + associated information query. This means we only hit the database once, but given the complexity of all these properties this will be difficult to do in entirety.
2. On the other extreme, we could load all tables into memory as [pandas dataframes](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html), and do all the joins in memory, which would be easier than figuring out a complex query for something like patient status. But this means we have to joins manually, not taking advantage of the database relationships we wrote (plus costing a ton of memory space).
3. A mix of the above. For simple relationships, we can write a query to tell django to join. For more complicated things we can load whole tables into memory, then do the filter/joins there. This is the easy solution, but has the potential for excessive memory consumption.

Some questions I have:

1. Where is `workup_set`? I see `self.workup_set` on the Patient model twice, but searching the code base I can't seem to find where the property is derived from.
2. What is the memory on the machine osler is deployed on (tiny MB, or GB?)
3. How many rows are there in the Patients and ActionItems tables?
Answers for 2 and 3 limit the degree to which we can just load entire tables into memory.

About timeline:
I'm gonna say this entire thing is a 3-4 week effort, because

- there are 8 properties
- only one (gender) is directly on the Patient table
- a lot of them are kinda complicated properties defined by functions
- every one needs to be rewritten to not hit the database again
- I am not familiar with django query language (how to use select_related, etc.)

I forgot that I won't be back home till next week, so I'm gonna put the estimate for rewriting every single property at 4-5 weeks from now.

That said, we should see small latency improvements for every property that does not require a db query. So there is an option of gradually rolling out small improvements, even if the big one will come from not looping over all patients.

Fixing this may remove the need for #131

**Comment by justinrporter** [comment]
Josephine, thanks for the awesome investigation of this issue. I buy your argument for what the problem is. I wonder if any of the queries you talk about are any worse than others---perhaps [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/) could help us actually profile this?

First, I was wondering how far you think `prefetch_related` [here](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#prefetch-related) would get us? My impression is that it's purpose is to avoid exactly this problem. I'm not sure how much memory this approach would cost, though.

There might also be some useful tricks/pre-built features that we could leverage described in the django docs for this [db optimization](https://docs.djangoproject.com/en/2.0/topics/db/optimization/).

Answers:
1. `workup_set` is automatically generated by the `ForeignKey` relationship to `Patient` in `Workup`. By default, an FK property will create a "[classname]_set" parameter in the target model.
2. The machine has 4GB RAM and 1GB swap.
3. There are 898 patients, 2470 action items, and 1008 workups.

**Comment by nosarcasm** [comment]
Ryan from EHHOP Tech here at Mount Sinai. Haven't looked specifically at your code but I have some ideas:

1. lazy='dynamic' in your database model should speed things up a bit (only hits the DB when it accesses that item). 
2. I would look into pagination. Flask has a good method of doing this. http://flask-sqlalchemy.pocoo.org/2.3/api/. Not sure how it works in Django but should be similar. 
3. Use asynchronous requests using DataTables to access the all patients data and show a loading spinner.

**Comment by justinrporter** [comment]
@nosarcasm hi Ryan! Welcome!

Those are some good ideas! Here are some thoughts:

1. The `lazy='dynamic'` semantic is used in SQLAlchemy, right? We're using the built-in Django ORM (for obvious reasons)... I don't know very much about SQLAlchemy, though. Anywhichway, I think the Django ORM QuerySet object does this by default--our working hypothesis is that issue is the reverse: the laziness means that we're hitting the db _too often_ when we lazily load each item linked by the backref. My impression is that what we're trying to do the equivalent of changing it to `lazy='joined'` but _for just this query_.
2. Yeah, so django REST framework (a Django library that makes it easy-ish to build API endpoints from models), and it definitely supports pagination ([here](http://www.django-rest-framework.org/api-guide/pagination/)). The reason we haven't done this already is that it makes the js more complex, but that may be kind of inevitable. 
3. The requests are actually already nearly all asynchronous, and this is definitely an option--@Josephine how hard would this be compared to just fixing the queries?

I mean, obviously, the optimal solution is to change the view to not suck, but these are some potentially effective temporizing measures...

**Comment by nosarcasm** [comment]
Thanks Justin! 

1. Ah, I see how that would be a problem if it is generating separate queries instead of pulling it all at once since the latency would be a nightmare. I wonder if osler would benefit from... (I really don't want to say it because it scares me) _CACHING_, but this would require some work to make sure it doesn't start displaying outdated information. 

I wonder if your page render times themselves are too slow - have you looked into this for your app? When I was working on a project a long time ago this was the culprit, not the DB, so I wonder if you've had a chance to profile it and measure how long each step takes. Dumping the raw JSON from the query results into a web page may be the fastest option as long as JS can format it fast enough on the client-side.

2. Pagination and JS libraries like DataTables that have built-in support for Django may be the way to go. For instance, we use DataTables to make the data view more manageable and keep page render times low.

**Comment by JoLBree** [comment]
Hi Ryan!

Some thoughts on the conversation:

1. Justin, thanks for the answers!
2. Thanks for the tip on `prefetch_related` as well, the docs for that mention `select_related` and they seem like tools in the same toolkit, one for 1-1 and one for 1-many relationships
3. Regarding db optimizations, the first things mentioned are indices and querysets. Indices are more likely to be the culprit if latency is bottlenecked by the time taken for a particular query, because the query has to join large tables using keys without indices. Querysets are what `prefetch_related` and `select_related` are about, and are about minimizing the number of round trips to the database which cost far more than the time for a particular query. In my brief diagnosis I had indices in mind and saw that most joins were simple joins to primary keys on other tables, and primary keys are automatically indexed. That said, if after dealing with the >thousands of I/O hits we still have latency issues we should look into missing indices.
4. Thanks for your thoughts Ryan! Regarding asynchrony, the table is essentially the only content on the page; a spinner would be a nice cosmetic stopgap until we get this fixed but it doesn't solve the underlying issue.
5. As for pagination, in this conversation I see three levels of pagination.

    - Ryan first mentioned pagination on the level of a queryset (Django-ORM)/basequery (SQLalchemy). The issue we have is not one of an extremely large table that we need to read out in batches, but that the table has many joins and secondary properties computed. Cutting the query into multiple batches of rows would quite possibly slow the query down, since we need to make separate joins for each batch. It also does not address the problem of multiple database round trips due to un-followed joins.
    - Justin then mentioned pagination on the level of the Django REST framework. This is usually used for people building microservices that return greater than tens of thousands of results, so that the users of these endpoints don't have to see all of them. In our case, the amount of data we are transmitting for the table to render is trivial.
    - Finally, Ryan mentioned pagination by front end libraries such as jQuery's DataTables. I am quite familiar with DataTables through work; and as you mention front end pagination would be useful if each row had some really fancy rendering and we were bottlenecked on generating those DOM nodes (or more frequently, for UI purposes if we wanted to cut down the table length). Our table and page is extremely bare bones and I am very doubtful that we are bottlenecked on front end rendering, as opposed to the screaming culprit of a crazy number of database round trips. That said, I do like the library and had it in mind for another feature we had discussed (searching the table), but that comes after dealing with this. In my mind the js shouldn't be complex.
5. On the note of caching, I see a few possible types of caching
    - Database retrieval caching, which is already handled by the Django ORM
    - REST endpoint caching, though as Ryan implies I'm not sure how we would define the set of things that trigger a re-pull since the properties of a patient row changes as people use our app
    - Some sort of manually handled caching that computes the all patients table every time we change a patient property, which would take more work to build than fixing the round trips and is also uglier from a design standpoint.

All that said and done, I'm going to work on reducing the number of round trips. There's been a great discussion here that I think is useful for further optimizations, but I'm going to take the screaming elephant out of the room first.

**Comment by JoLBree** [comment]
Track progress on the columns, which quite conveniently start with the easiest:

- [ ] Patient Name
- [ ] Age/Gender
- [ ] Case Managers
- [ ] Latest Activity
- [ ] Next AI Due
- [ ] Attestation

**Comment by justinrporter** [comment]
Yo that's super cool! I wonder what happens if you populate the db with more patients (like, say, 100)? I bet there are some queries that scale more poorly than others...
