### ISSUE TITLE
Add a country to the address field

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#20]
We sometimes get patients who are not from the US. We should have a country field (defaulted to USA)--it could maybe even be free text. @radhikajain ?

**Comment by radhikajain** [comment]
Great idea. Am I tagged on this one because I need to do it? Do I know how?

On Sep 5, 2015, at 9:43 PM, "Justin R. Porter" <notifications@github.com<mailto:notifications@github.com>> wrote:


We sometimes get patients who are not from the US. We should have a country field (defaulted to USA)--it could maybe even be free text. @radhikajain<https://github.com/radhikajain> ?

-
Reply to this email directly or view it on GitHub<https://github.com/SaturdayNeighborhoodHealthClinic/osler/issues/20>.

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by justinrporter** [comment]
I guess the question was how do we want countries to be represented? Do we care if they are just free text? I hate those country dropdowns from a usability perspective...

**Comment by radhikajain** [comment]
Right, although I suppose the only issue with free text is that everyone might put USA in differently. Could this be one of those in which we have a limited set of options in the drop down and then add to it? Say start with just USA, and then in the help text tell them to email us as soon as they need a new country and we'll add it on the admin side?

**Comment by justinrporter** [comment]
Exactly. The default would be USA and the user would have to actively change it to some other variant. Not that it's impossible, but it will cut down on variations by a lot. Also, this field will be editable by users at any time with the 'edit patient details' pencil on the pt chart view.

**Comment by radhikajain** [comment]
Okay, I like that plan.

**Comment by justinrporter** [comment]
Done.
