### ISSUE TITLE
Document Upload

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#32]
Is it possible to upload multiple pages at once as a single "document"

**Comment by justinrporter** [comment]
@nakul2234 could we make this one a next goal? I also want to look into uploading pdfs with the FileField (rather than ImageField).

**Comment by nakul2234** [comment]
Ideally, once we get the scanner, all the files that need to be one document can be uploaded as a single pdf. I think we should just do a file upload instead of an image upload since it would allow for Pdf and images (though they would not be displayed on the web page which would mean people would have to download them).

**Comment by ecd25** [comment]
I'd like to be able to upload PDFs also, justin said this might be
complicated though.

On Thu, Sep 17, 2015 at 11:19 AM, Nakul Shah <notifications@github.com>
wrote:

> Ideally, once we get the scanner, all the files that need to be one
> document can be uploaded as a single pdf. I think we should just do a file
> upload instead of an image upload since it would allow for Pdf and images
> (though they would not be displayed on the web page which would mean people
> would have to download them).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SaturdayNeighborhoodHealthClinic/osler/issues/32#issuecomment-141137669>
> .
>



-- 
Emily Davis

Washington University School of Medicine
Class of 2018

SA Cell Phone +27 (61) 640 4194
US Cell Phone: +1 (818) 523 7003
Email: emilychristinedavis@gmail.com
