### ISSUE TITLE
UI Beautification

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#51]
- [x] Grouping of Notes in an intelligent way
- [x] Hide "Followup" button from Clinical/Preclinical/Attending
- [x] PMH/PSH on workup detail has stray '}}'
- [ ] Regroup patient lists based upon latest activity
- [x] Patient activation on list view
- [x] Referral Type and Referral Location still print with `pttrack.*.None` (UPDATE: the view was not saving the m2m field on updates, that was fixed as well -nakul2234)
- [x] On the home page of Coordinators, add a list of all the tasks that are upcoming
- [x] The signing of a workup should not inactivate patient. This encourages coordinators to review patients before closing them.

**Comment by justinrporter** [comment]
hide followup addressed in 80f5bae5389f455cc6b82020d0a55e6d6b7bcd7d

**Comment by justinrporter** [comment]
I'm wondering if the grouping of notes in an intellegent way will need to impact our schema design--I think it's silly that action items and their followup closeouts are not related in the db.

**Comment by nakul2234** [comment]
I do not think Regrouping by latest activity is needed at this point. Since now the coordinators are activating patients, and that decides what patients the attendings and clinicals see, grouping the list more will likely just make it more complicated. Everything else I checked-off was done in the latest pull request I have.

**Comment by justinrporter** [comment]
Sounds good!
