### ISSUE TITLE
Wording change?

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/osler#97]
I'm a little concerned that we call the demographic data 'survey' information. Mostly because surveys often need consent and we do not have any kind of consent document for our intake form, or because surveys seem optional and this is not information I want patients or coordinators to think of as optional (ok, so it isn't technically required either, but it is SUPER DUPER helpful to have and I don't want us to miss it).

Perhaps the section currently labeled 'Demographic Information' could be labeled "Intake Information" and the section currently labelled "Patient Survey Data" or "Demographic Survey Data" could just be labeled "Patient Demographic Information" or "Demographics" etc.

This does not need to be a high priority obviously.

**Comment by justinrporter** [comment]
Hm. Ok--I actually liked "survey" data, but let's talk offline about this. "Intake" is a dangerous word, because "intake" is currently used to indicate the information that's required to create a patient, whereas this data exists separately, but alongside, a patient. The system that implements this data could be equally used to implement a system by which *any* kind of survey is attached to patient data (e.g. "how did we do today" kinds of stuff)

I think that there are other ways to indicate importance (remember the "Whoa! No demographics data!" stuff from launch?) and that we should investigate them, or come up with another name. At some point let's get together and put our thinking caps on.

**Comment by justinrporter** [comment]
Implemented as 'demographics'.
